name: Publish Formation

on:
  schedule:
    - cron: "30 6 * * 5"   # 06:30 UTC ≈ 08:30 Europe/Rome (ora legale)
    - cron: "0 7 * * 5"    # 07:00 UTC ≈ 09:00 Europe/Rome (ora legale)
  workflow_dispatch: {}     # bottone "Run workflow"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Rome
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # Aggiorna i rating (fallback se mancano le tue odds)
      - name: Update team ratings
        run: node scripts/update-team-ratings.js || echo "ratings skipped"

      # Pubblica: se schedulato rispetta la finestra; se manuale forza
      - name: Publish (scheduled)
        if: github.event_name != 'workflow_dispatch'
        run: |
          node scripts/publish-formation.js
          node scripts/publish-top5.js

      - name: Publish (manual force)
        if: github.event_name == 'workflow_dispatch'
        run: |
          node scripts/publish-formation.js --force
          node scripts/publish-top5.js --force

      - name: Commit & push if changed (with rebase)
        run: |
          git config user.name "FantaBot"
          git config user.email "bot@users.noreply.github.com"
          git fetch origin main
          git pull --rebase origin main || true
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "chore: publish formazione + top5 (auto)"
            git push origin HEAD:main
          else
            echo "Nessuna modifica."
          fi
